### ISSUE TITLE
Kundera multiple node support

### ISSUE THREAD

**Issue by eld0** [Impetus/kundera#249] opened 2013-04-26 08:39 UTC
Hi,
Is there any posibility to set multiple node for Kundera? It's a important feature for us, because we plan to use Cassandra + Kundera on production level and balancing is very critical. Currently we have a workarounds but most preffered way to have native support from Kundera.
Thanks!

cassandra 1.1.5
kundera 2.4

**Comment by mevivs** [comment] 2013-04-26 08:41
Kundera 2.5 will be releasing in coming week. Work on load balancer and multiple node support is planned for future releases and still in very early stages.

Sincerely,
-Vivek

**Comment by eld0** [comment] 2013-04-26 08:58
Thanks for your quick response.
Will be wait for any updates!

**Comment by mevivs** [comment] 2013-04-26 09:02
Thanks. We will try to push it on priority. Till then, if other workarounds works for you and in case of any issues regarding Kundera for moving into production. Please feel free to raise issues for quick support!

Cheers,
-Vivek

**Comment by pires** [comment] 2013-05-03 16:34
+1

@eld0 can you provide details on your workaround?

**Comment by mevivs** [comment] 2013-05-03 16:46
You may try using HAProxy as a workaround.

-Vivek

**Comment by pires** [comment] 2013-05-03 16:50
Can you detail further? I mean, I write a row to a different host, based on the selected load-balancing algorithm and then the machine replicates to other nodes?

Can I have a cluster but use it in Kundera as a single node?

**Comment by mevivs** [comment] 2013-05-03 16:57
Not really. You can use as a load balancer and say you a cassandra cluster of 3 nodes. Replication would be handled by Cassandra conifgurations itself(based on selected strategy and replication factor). Configure Kundera with ip where HAProxy is installed and rest it will route to your cassandra nodes. You can find multiple tutorials for such things. Here is one of them:
http://blog.rimuhosting.com/2011/07/05/easy-web-serve-load-balancing-with-haproxy/

Hope it helps.

-Vivek

**Comment by pires** [comment] 2013-05-03 17:31
I use HAProxy a lot and know how it works, both for HTTP servers and TCP and I think you just basically said almost the same I assumed. But clarifying:

1) We have two configurations, Kundera and each node configuration, right?

2) If yes, Kundera configuration should map a single host (an IP/hostname with HAProxy) or should it have the information about all the nodes, replication, etc.?

3) The host to which HAProxy delivers the request will replicate as configured locally (in the node), right?

**Comment by mevivs** [comment] 2013-05-03 17:36
Ok.
1) We have two configurations, Kundera and each node configuration, right?
`
Yes
`
2) If yes, Kundera configuration should map a single host (an IP/hostname with HAProxy) or should it have the information about all the nodes, replication, etc.?
``
Should map to single host.

```
3) The host to which HAProxy delivers the request will replicate as configured locally (in the node), right?

``
Yes
```

-Vivek

**Comment by pires** [comment] 2013-05-03 17:50
Thanks @mevivs. Your help has been truly valuable to me!

**Comment by eld0** [comment] 2013-06-05 08:25
Hi,
Do you have any news about this enhancement? When you plan to release it?

**Comment by pires** [comment] 2013-06-05 08:26
AFAIK, this is in the works and should be included in 2.6.

**Comment by dobarskyy** [comment] 2013-06-06 08:25
Hi, we also are very intrested in this  - could you please clarify if this still goes to 2.6 which is in 8 days?

**Comment by mevivs** [comment] 2013-06-06 08:41
Yes. This will be released in 2.6. I will post an update once this is checked-in in current trunk.

-Vivek

**Comment by mevivs** [comment] 2013-06-11 07:23
Multiple node support has been added in Kundera for Cassandra. Please refer https://github.com/impetus-opensource/Kundera/wiki/Using-multiple-node-support-and-load-balancing-policy-in-Kundera 
for more details.   

Will be releasing with 2.6

-Vivek

**Comment by eld0** [comment] 2013-06-11 07:42
Great news! I'll check that. 
Big thanks!

**Comment by KunderaUser** [comment] 2013-06-12 13:07
I am trying out the multiple node support.  I have a 2 node cassandra cluster.

Datacenter: datacenter1

Address      Rack        Status State   Load            Owns                Token
                                                                            0
192.168.1.8  rack1       Up     Normal  63.14 KB        50.00%              -9223372036854775808
192.168.1.6  rack1       Up     Normal  96.22 KB        50.00%              0

If both of the nodes in the cluster are up then writes and reads using Kundera succeed, however if I shut one of the nodes down then writes fail with the following exception.

08:21:25,215  INFO KunderaPersistence:55 - Loading Core

08:21:25,218  INFO CoreLoader:41 - Loading Kundera Core Metdata ... 

08:21:25,221  INFO KunderaPersistence:104 - Loading Application MetaData and Initializing Client(s) For Persistence Unit(s) cassandra_pu

08:21:25,226  INFO PersistenceUnitConfiguration:75 - Loading Metadata from persistence.xml ...

08:21:25,303  INFO PersistenceUnitConfiguration:95 - Finishing persistence unit metadata configuration ...

08:21:25,304  INFO MetamodelConfiguration:162 - No class to scan for persistence unit cassandra_pu. Entities will be loaded from classpath/ context-path

08:21:25,382  INFO ClientMetadataBuilder:34 - Loading client factory for persistence unit cassandra_pu

08:21:25,383  INFO ClientResolver:73 - Initializing client factory for: cassandra_pu

08:21:25,393  INFO ClientResolver:136 - Finishing factory initialization

08:21:25,393  INFO SchemaConfiguration:106 - Configuring schema export for : cassandra_pu

08:21:25,617  WARN CassandraPropertyReader:158 - No data store configuration found, returning null.

08:21:25,617  WARN CassandraPropertyReader:251 - No column family schema found, returning null.

08:21:25,628 ERROR CassandraSchemaManager:397 - Error while opening socket for host  { }, Caused by: . 

org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused

at org.apache.thrift.transport.TSocket.open(TSocket.java:185)

at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.initiateClient(CassandraSchemaManager.java:390)

at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:110)

at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:147)

at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:159)

at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:45)

at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:352)

at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:116)

at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)

at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)

at javax.persistence.Persistence.createEntityManagerFactory(Unknown Source)

Caused by: java.net.ConnectException: Connection refused

at java.net.PlainSocketImpl.socketConnect(Native Method)

at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)

at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)

at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:432)

at java.net.Socket.connect(Socket.java:529)

at org.apache.thrift.transport.TSocket.open(TSocket.java:180)

... 38 more

08:21:32,916  INFO GenericClientFactory:102 - Loading client metadata for persistence unit : cassandra_pu

08:21:32,916  INFO GenericClientFactory:106 - Initializing client for persistence unit : cassandra_pu

08:21:32,918  WARN CassandraPropertyReader:158 - No data store configuration found, returning null.

08:21:32,919  WARN CassandraPropertyReader:268 - No connection properties found, returning none.

08:21:32,920  INFO GenericClientFactory:327 - Using default load balancer {} . ROUNDROBIN

08:21:32,921  WARN CassandraPropertyReader:158 - No data store configuration found, returning null.

08:21:32,936  WARN CassandraPropertyReader:158 - No data store configuration found, returning null.

08:21:32,936  WARN CassandraPropertyReader:268 - No connection properties found, returning none.

08:21:32,952  INFO GenericClientFactory:110 - Constructing pool for persistence unit : cassandra_pu

08:21:32,952  INFO PelopsClientFactory:89 - Creating pool

08:21:32,958  INFO Cluster:162 - Dynamic node discovery is disabled, using [192.168.1.6] as a static list of nodes

08:21:32,958  INFO PelopsClientFactory:119 - Initializing connection pool for keyspace grid, host 192.168.1.6,port 9160.

08:21:32,966  INFO CommonsBackedPool:121 - Initialising pool configuration policy: Config{maxActivePerNode=20, maxTotal=-1, maxIdlePerNode=10, minIdlePerNode=10, maxWaitForConnection=4000, testConnectionsWhileIdle=true, timeBetweenScheduledMaintenanceTaskRunsMillis=60000, nodeDownSuspensionMillis=10000}

08:21:32,966  INFO CommonsBackedPool:124 - Initialising pool node selection strategy: org.scale7.cassandra.pelops.pool.LeastLoadedNodeSelectionStrategy@626bd9e0

08:21:32,967  INFO CommonsBackedPool:127 - Initialising pool node suspension strategy: org.scale7.cassandra.pelops.pool.NoOpNodeSuspensionStrategy@451710be

08:21:32,967  INFO CommonsBackedPool:130 - Initialising pool connection validator: org.scale7.cassandra.pelops.pool.DescribeVersionConnectionValidator@2c6c5356

08:21:32,975  INFO CommonsBackedPool:146 - Pre-initialising connections for nodes: [192.168.1.6:9160]

08:21:32,975  INFO CommonsBackedPool:423 - Adding node '192.168.1.6' to the pool...

08:21:33,013  INFO CommonsBackedPool:71 - Registering MBean 'com.scale7.cassandra.pelops.pool:type=PooledNode-grid-192.168.1.6'...

08:21:33,017  INFO CommonsBackedPool:168 - Running maintenance tasks during initialization...

08:21:33,017  INFO CommonsBackedPool:176 - Configuring scheduled tasks to run every 60000 milliseconds

08:21:33,019  INFO CommonsBackedPool:161 - Registering MBean 'com.scale7.cassandra.pelops.pool:type=Pool-grid'...

08:21:33,020  INFO Pelops:72 - Pelops adds new pool 192.168.1.6:9160:grid

08:21:33,022  INFO Cluster:162 - Dynamic node discovery is disabled, using [192.168.1.8] as a static list of nodes

08:21:33,022  INFO PelopsClientFactory:119 - Initializing connection pool for keyspace grid, host 192.168.1.8,port 9160.

08:21:33,022  INFO CommonsBackedPool:121 - Initialising pool configuration policy: Config{maxActivePerNode=20, maxTotal=-1, maxIdlePerNode=10, minIdlePerNode=10, maxWaitForConnection=4000, testConnectionsWhileIdle=true, timeBetweenScheduledMaintenanceTaskRunsMillis=60000, nodeDownSuspensionMillis=10000}

08:21:33,022  INFO CommonsBackedPool:124 - Initialising pool node selection strategy: org.scale7.cassandra.pelops.pool.LeastLoadedNodeSelectionStrategy@3987f9f1

08:21:33,022  INFO CommonsBackedPool:127 - Initialising pool node suspension strategy: org.scale7.cassandra.pelops.pool.NoOpNodeSuspensionStrategy@e2a5ab9

08:21:33,022  INFO CommonsBackedPool:130 - Initialising pool connection validator: org.scale7.cassandra.pelops.pool.DescribeVersionConnectionValidator@7eaa2ef2

08:21:33,022  INFO CommonsBackedPool:146 - Pre-initialising connections for nodes: [192.168.1.8:9160]

08:21:33,023  INFO CommonsBackedPool:423 - Adding node '192.168.1.8' to the pool...

08:21:33,023  INFO CommonsBackedPool:71 - Registering MBean 'com.scale7.cassandra.pelops.pool:type=PooledNode-grid-192.168.1.8'...

08:21:33,284  INFO CommonsBackedPool:168 - Running maintenance tasks during initialization...

08:21:33,299  INFO CommonsBackedPool:176 - Configuring scheduled tasks to run every 60000 milliseconds

08:21:33,299  WARN CommonsBackedPool:157 - MBean 'com.scale7.cassandra.pelops.pool:type=Pool-grid' is already registered, removing...

08:21:33,299  INFO CommonsBackedPool:161 - Registering MBean 'com.scale7.cassandra.pelops.pool:type=Pool-grid'...

08:21:33,300  INFO Pelops:72 - Pelops adds new pool 192.168.1.8:9160:grid

08:21:33,311  INFO EntityManagerImpl:987 - Returning client instance for:cassandra_pu

08:21:33,311  INFO PelopsClientFactory:151 - Initializing pelops client for persistence unit cassandra_pu

08:21:33,325  WARN CassandraPropertyReader:158 - No data store configuration found, returning null.

08:21:33,349  WARN CommonsBackedPool:334 - A TTransportException was thrown while attempting to create a connection to '192.168.1.6'.  This node will be suspended for 10000ms.  Trying another node...

08:21:37,386 ERROR CommonsBackedPool:351 - Failed to get a connection within the configured wait time because there are no available nodes. This possibly indicates that either the suspension strategy is too aggressive or that your cluster is in a bad way.

com.impetus.kundera.KunderaException: org.scale7.cassandra.pelops.exceptions.NoConnectionsAvailableException: Failed to get a connection within the configured max wait time.

at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:176)

Caused by: org.scale7.cassandra.pelops.exceptions.NoConnectionsAvailableException: Failed to get a connection within the configured max wait time.

at org.scale7.cassandra.pelops.pool.CommonsBackedPool.getConnectionExcept(CommonsBackedPool.java:356)

at org.scale7.cassandra.pelops.pool.CommonsBackedPool.getConnection(CommonsBackedPool.java:289)

at com.impetus.client.cassandra.pelops.PelopsClientFactory.getConnection(PelopsClientFactory.java:260)

at com.impetus.client.cassandra.pelops.PelopsClient.getConection(PelopsClient.java:845)

at com.impetus.client.cassandra.pelops.PelopsClient.getConection(PelopsClient.java:90)

at com.impetus.client.cassandra.CassandraClientBase.getRawClient(CassandraClientBase.java:1627)

at com.impetus.client.cassandra.pelops.PelopsClient.onPersist(PelopsClient.java:453)

at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:85)

at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:182)

at com.impetus.kundera.graph.Node.flush(Node.java:523)

at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:444)

at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:156)

at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:170)

Below is my configuration for persistence.xml and KunderaLoadConfig.xml

Please let me know if I am doing something wrong.

![screen shot 2013-06-12 at 9 10 05 am](https://f.cloud.github.com/assets/4679436/642597/83b40d10-d361-11e2-8f73-b2fa2898617a.png)

![screen shot 2013-06-12 at 9 11 28 am](https://f.cloud.github.com/assets/4679436/642602/a63f9d86-d361-11e2-92ad-7a41a4b94e09.png)

**Comment by mevivs** [comment] 2013-06-12 15:28
Last reported issue is related to Pelops only. Reason is underlying Pelops API does not provide a way to test connection until you really execute a call with thrift and not sure whether they will plan to implement this as well.

I suggest to use, ThriftClientFactory in place of PelopsClientFactory in persistence.xml.

**Comment by KunderaUser** [comment] 2013-06-12 19:50
The issue was that Kundera DDL was creating a keyspace with SimpleStrategy.  This needs to change to expose these settings via the persistence.xml

Once I changed the keyspace to Network Topology Strategy the connection pooling worked.

**Comment by Gargee** [comment] 2013-06-21 22:07
Hi We too are planning to use Kundera+Cassandra for our production.Looks like this feature has been made available recently.A sample project with the required configurations will be of immense help to us here.
We are planning to use a 6 node Cassandra ring with the same port.
I see in the configuration file there is a property 
 "//<//property name="kundera.pool.size.max.active" value="33"></property//> //" .
It will be really helpful if we can get advise on the  optimal values for the connection pooling.

**Comment by mevivs** [comment] 2013-06-22 03:28
I will publish a blog and share a link with you on this.

-Vivek

**Comment by mevivs** [comment] 2013-06-23 04:00
Update wiki for https://github.com/impetus-opensource/Kundera/wiki/Using-multiple-node-support-and-load-balancing-policy-in-Kundera.

Hope this helps.

-Vivek

**Comment by Gargee** [comment] 2013-06-23 21:24
thanks Vivek

**Comment by Gargee** [comment] 2013-06-26 21:16
hi Vivek ,
I was trying to develop my multinode supported application with kundera 2.6+Cassandra 1.2.
Previously i was using kundera 2.5,but now when i try changing the version to 2.6 in my POM.xml i get this  below error:-
INFO] ------------------------------------------------------------------------
[INFO] Building KunderaDAL 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.impetus.client:kundera-cassandra:jar:2.6 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.439s
[INFO] Finished at: Wed Jun 26 14:12:44 PDT 2013
[INFO] Final Memory: 3M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project KunderaDAL: Could not resolve dependencies for project KunderaDAL:KunderaDAL:jar:0.0.1-SNAPSHOT: Failure to find com.impetus.client:kundera-cassandra:jar:2.6 in http://kundera.googlecode.com/svn/maven2/maven-missing-resources was cached in the local repository, resolution will not be reattempted until the update interval of kundera-missing has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

my POM.xml:-



<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">



```
<modelVersion>4.0.0</modelVersion>
```



```
<groupId>KunderaDAL</groupId>
<artifactId>KunderaDAL</artifactId>
<version>0.0.1-SNAPSHOT</version>
<packaging>jar</packaging>
```



```
<name>KunderaDAL</name>
<url>http://maven.apache.org</url>
```



```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
<dependencies>
    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.10</version>
        <scope>test</scope>
    </dependency>

    <!--My pom-->
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring</artifactId>
        <version>2.5.6</version>
    </dependency>
    <dependency>
        <groupId>com.impetus.client</groupId>
        <artifactId>kundera-cassandra</artifactId>
        <version>2.6</version>
    </dependency>
</dependencies>
<repositories>
    <repository>
        <id>kundera-missing</id>
        <name>Kundera Public Missing Resources Repository</name>
        <url>http://kundera.googlecode.com/svn/maven2/maven-missing-resources</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
    <repository>
        <id>sonatype-nexus</id>
        <name>Kundera Public Repository</name>
        <url>https://oss.sonatype.org/content/repositories/releases</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
```

</project>
  -->

**Comment by pires** [comment] 2013-06-26 22:26
Kundera 2.6 is not released yet. But you can hack your way into it!
1. Clone Kundera repository
2. In the folder you just cloned to, execute:
   `mvn clean install -DskipTests`
3. Edit your project _pom.xml_ and set Kundera version to _2.6-SNAPSHOT_. Save it.
4. Build your project and give it a go!

**Comment by Gargee** [comment] 2013-06-26 22:34
When is kundera 2.6  likely to be released?  july? Actually we are planning to roll it into our production code ..so the time line is important for us

**Comment by mevivs** [comment] 2013-06-27 02:41
It will be releasing by this weekend.

-Vivek

**Comment by eld0** [comment] 2013-07-03 08:28
Just checked version from trunk. Works as expected, great thanks for your job! But we still waiting for release, because we can't promote this version until it'll be placed at maven central repo.
Is there any changes in the release timeline?

**Comment by mevivs** [comment] 2013-07-03 08:43
Will be releasing by 7th july.

-Vivek

**Comment by mevivs** [comment] 2013-07-03 08:47
btw, using Kundera for? 
Would be great if you can spend few minutes for:
http://www.surveymonkey.com/s/BMB9PWG

Cheers,
-Vivek

**Comment by eld0** [comment] 2013-07-03 09:25
We are going with kundera to production (companys' internal security system). I'd done yours survey.
If there any other things that can help you - doesn't hesitate to ask.

**Comment by mevivs** [comment] 2013-07-06 19:52
Releasing with 2.6

-Vivek

**Closed as completed by mevivs** 2013-07-06 19:52 UTC

**Comment by pires** [comment] 2013-07-08 08:26
Works for me. Thanks.

**Comment by mevivs** [comment] 2013-07-10 07:13
@eld0 
Thanks for taking your time for survey/feedback. It will be great  if you can brief about Kundera's usage in form of an email? My email id is : vivek.mishra@impetus.co.in

Thanks again for your time.

-Vivek

**Comment by nikitaGoyal2** [comment] 2016-01-13 10:07
Multiple nodes : Kundera.nodes configuration for OracleNosql is not working. Does Kundera support multiple nodes for OracleNosql or not?
