### ISSUE TITLE
Kundera many-to-many relationship update not working

### ISSUE THREAD

**Issue by absidish** [Impetus/kundera#699] opened 2015-02-04 08:35 UTC
Hello !  I`m using Kundera 2.15 with Cassandra 2.0.4 
Create, Read, Delete works successfully , the problem with Update. 

I have two entities : 

```
@Entity
@Table( name = "role", schema = "kunderaexamples@twissandra" )
@IndexCollection( columns = { @Index( name = "is_default" ), @Index( name = "name" ) } )
public class Role
{
    @Id
    @Column( name = "role_id" )
    @GeneratedValue( strategy = GenerationType.TABLE )
    private Long roleId;

    @Column( name = "name" )
    private String name;

    @Column( name = "is_default" )
    private boolean defaultRole;

    @ManyToMany( cascade = { CascadeType.ALL }, fetch = FetchType.EAGER )
    @JoinTable( name = "role_permission",
            joinColumns = { @JoinColumn( name = "role_id" ) },
            inverseJoinColumns = { @JoinColumn( name = "permission_id" ) } )
    private List<Permission> permissions;

    @Override
    public int hashCode()
    {
        return Objects.hashCode( this.roleId );
    }

    @Override
    public boolean equals( final Object obj )
    {
        if ( obj instanceof Role )
        {
            final Role other = ( Role ) obj;
            return Objects.equals( this.roleId, other.roleId );
        }
        return false;
    }

    public void addPermission( Permission permission )
    {
        if ( permissions == null )
        {
            permissions = new ArrayList<Permission>();
        }
        permissions.add( permission );
    }

    public void removePermission( Permission permission )
    {
        if ( permissions != null )
        {
            permissions.remove( permission );
        }
    }

@Entity
@Table(name = "permission", schema = "kunderaexamples@twissandra")
@IndexCollection(columns = { @Index(name = "name") })
public class Permission 
{
    @Id
    @Column(name = "permission_id")
    @GeneratedValue(strategy = GenerationType.TABLE)
    private Long permissionId;

    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "description", nullable = true)
    private String description;

    @Override
    public boolean equals( final Object o )
    {
        if ( this == o )
        {
            return true;
        }
        if ( !( o instanceof Permission ) )
        {
            return false;
        }

        final Permission that = ( Permission ) o;

        if ( !( permissionId == that.permissionId ) )
        {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode()
    {
        return Objects.hashCode( this.permissionId );
    }

```

File pom.xml  :

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.impetus.poc</groupId>
  <artifactId>KunderaPOC</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>KunderaPOC</name>
  <url>http://maven.apache.org</url>
  <repositories>
    <repository>
      <id>sonatype-nexus</id>
      <name>Kundera Public Repository</name>
      <url>https://oss.sonatype.org/content/repositories/releases</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>riptano</id>
      <name>riptano</name>
      <url>http://mvn.riptano.com/content/repositories/public</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>com.impetus.kundera.client</groupId>
      <artifactId>kundera-cassandra</artifactId>
      <version>2.15</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

and persistence.xml file : 

```
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
             version="2.0">
  <persistence-unit name="twissandra">
    <provider>com.impetus.kundera.KunderaPersistence</provider>

    <class>model.Role</class>
    <class>model.Permission</class>
    <properties>
      <property name="kundera.nodes" value="localhost" />
      <property name="kundera.port" value="9160" />
      <property name="kundera.keyspace" value="kunderaexamples" />
      <property name="kundera.dialect" value="cassandra" />
      <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
      <property name="kundera.ddl.auto.prepare" value="update" />
    </properties>
  </persistence-unit>
</persistence>
```

and use : 

```
private static void create()
    {
        Role role = new Role();
        role.setName( "testName10" );
        role.setDefaultRole( true );

        Role role1 = new Role();
        role1.setName( "testName1" );
        role1.setDefaultRole( false );

        Role role2 = new Role();
        role2.setName( "testName2" );
        role2.setDefaultRole( true );

        Role role3 = new Role();
        role3.setName( "testName3" );
        role3.setDefaultRole( false );

        Permission permission = new Permission( "testName0" );
        Permission permission1 = new Permission( "testName1" );
        Permission permission2 = new Permission( "testName2" );
        Permission permission3 = new Permission( "testName3" );


        role.addPermission( permission1 );
        role1.addPermission( permission2 );
        role2.addPermission( permission );
        role3.addPermission( permission3 );


        EntityManagerFactory emf = Persistence.createEntityManagerFactory( "twissandra" );
        EntityManager em = emf.createEntityManager();

        em.persist( role );
        em.persist( role1 );
        em.persist( role2 );
        em.persist( role3 );

        em.flush();

        em.close();
        emf.close();
    }

    private static void update()
    {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory( "twissandra" );
        EntityManager em = emf.createEntityManager();

        Query q = em.createQuery( "select p from Role p" );
        List<Role> roles = q.getResultList();
        Permission permission = null;

        for ( Role role : roles )
        {
            permission = role.getPermissions().get( 0 );
            role.removePermission( permission );
            em.merge( role );
            //em.persist( role );
        }
        em.flush();

       Query qq = em.createQuery( "select p from Role p" );
        List<Role> ps1 = qq.getResultList();

        em.close();
        emf.close();
    }
```

after running update();
Each Role contains permissions, that I removed.

**Comment by karthikprasad13** [comment] 2015-02-04 13:54
@absidish 

We were able to reproduce the issue and it seems to be a bug. However, update works with Kundera when you are changing the fields of the relation objects. Marking it as an issue , will add the fix soon !

-Karthik

**Comment by karthikprasad13** [comment] 2015-04-23 06:50
@absidish 

Please use CQL version 3 for achieving the same. One of the ways you can do this is:

```
  EntityManagerFactory emf = Persistence.createEntityManagerFactory("cassandra_pu");
  EntityManager em = emf.createEntityManager();
  em.setProperty("cql.version", "3.0.0");
```

**Comment by absidish** [comment] 2015-04-23 19:45
Thank you,
with regards
Sydyk

**Comment by chhavigangwal** [comment] 2015-05-09 14:45
Closing with Kundera-2.17 release

**Closed as completed by chhavigangwal** 2015-05-09 14:45 UTC
Labels: Fix

**Comment by prasanthdreamjava** [comment] 2017-07-27 15:37
Hi I am using cql 3.0 version.

I am also try to do many to many relationship. I followed same code what absidish try.
While inserting role_permission table automatically "key" cloumn added in the insert query.
Ex:
BEGIN BATCH  INSERT INTO "role_permission" (key, "persmission_id", "role_id") VALUES('1c7877e0-72df-11e7-af70-39f553d29ed4ROLE', 1c7877e0-72df-11e7-af70-39f553d29ed4, 'ROLE');

I dnt know where kundera taking key as cloumn.

And when i add the batch query size in persistence-unit role_persmission insertion not happening.
Please help me on this.

Thanks,
Prasanth
