### ISSUE TITLE
JPQL: 'count' not working for mongodb and elasticsearch

### ISSUE THREAD

**Issue by dreamingo88** [Impetus/kundera#824] opened 2016-01-06 03:31 UTC
## 1. persistence.xml:

```
<persistence-unit name="MONGO_PU">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>models.Category</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="27017" />
        <property name="kundera.keyspace" value="xplayks" />
        <property name="kundera.dialect" value="mongodb" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.mongodb.MongoDBClientFactory" />
        <property name="kundera.ddl.auto.prepare" value="update" />
        <property name="kundera.show.query" value="true" />

        <property name="kundera.indexer.class" value="com.impetus.client.es.index.ESIndexer" />
    </properties>
</persistence-unit>

<persistence-unit name="MONGO_NTV">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>models.Category</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="27017" />
        <property name="kundera.keyspace" value="xplayks" />
        <property name="kundera.dialect" value="mongodb" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.mongodb.MongoDBClientFactory" />
        <property name="kundera.ddl.auto.prepare" value="update" />
        <property name="kundera.show.query" value="true" />
    </properties>
</persistence-unit>
```
## 2. Category.java:

```
@Id
@Column(name="id")
public String id;

@Column(name="name")
public String name;

@Column(name="code")
public String code;

@Column(name="description")
public String description;'
```
## 3. createCategory() using MONGO_PU:

```
for(int i = 9000; i < 9030; i++) {
    Category ctg = new Category();
    ctg.name = "just a simple demo " + i;
    ctg.code = "democode";
    ctg.description = "just a demo, using mongodb and elasticsearch";

    em.persist(ctg);
}
```
## 4. findCategory() using MONGO_PU (it using elasticsearch to execute the queries  auto):

```
Query q = em.createQuery("select ctg.id, ctg.name, ctg.code from Category ctg where ctg.code = 'democode'", Category.class);
q.setFirstResult(0);
q.setMaxResults(20);
List<Category> ctgList = q.getResultList();
System.out.println("================="+ctgList.size()); //print 20

q.setFirstResult(20);
q.setMaxResults(20);
ctgList = q.getResultList(); //the same list as above.
System.out.println("================="+ctgList.size()); //print 20, the same result as above. the right value should be 10.
```

Question 1:  i think q.setFirstResult(20) doesn't effective. why?

```
Query query = em.createQuery("select count(ctg) from Category ctg where ctg.code = 'democode'");
String count = query.getResultList().get(0).toString();
System.out.println("================="+count); //print 336, it's very very strange. the right value should be 30
```

Question 2: what's the problem?
## 5. findCategory() using MONGO_NTV:

```
Query query = em.createQuery("select count(ctg) from Category ctg where ctg.code = 'democode'");
String count = query.getResultList().get(0).toString();
System.out.println("================="+count); //print 'just a simple demo ...', it's very very strange, the right value should be 30, 
```

Question 3: what's the problem? 'count' not supported by mongodb?

**Comment by devender-yadav** [comment] 2016-01-06 05:42
@dreamingo88 

Please share Kundera version & Mongo version. Also, the dependencies of Kundera added by you in `pom.xml`.

-Dev

**Comment by devender-yadav** [comment] 2016-01-06 06:58
@dreamingo88 

 `q.setFirstResult()` &  `q.setMaxResults()` are supported in kundera-mongoDB. So, no need to use Elasticsearch for this.  Refer [this](https://github.com/impetus-opensource/Kundera/blob/4bc732ebeea971d0449e4bf67a70023e83a72a8b/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java#L765) testcase.

Count is also supported but in native way. So again no need to use Elasticsearch for this. Try this:

```
List count = em.createNativeQuery("db.Category.find({\"code\":\"democode\"}).count()",Category.class).getResultList();
System.out.println(count.get(0).toString());
```

Check [testcase](https://github.com/impetus-opensource/Kundera/blob/4bc732ebeea971d0449e4bf67a70023e83a72a8b/src/kundera-mongo/src/test/java/com/impetus/client/crud/PersonMongoTest.java#L575) for more details.

-Dev

**Comment by dreamingo88** [comment] 2016-01-06 10:18
@devender-yadav thank you for your reply.
i use kundera 3.2, mongo 3.0, elasticsearch 1.7.

**Comment by devender-yadav** [comment] 2016-01-06 10:48
@dreamingo88 

we am not able to reproduce issues (_mentioned by you_)  at our end. You can mail your sample project at kundera@impetus.co.in  so that we can reproduce the issue at our end. 

-Dev

**Comment by dreamingo88** [comment] 2016-01-06 12:21
@devender-yadav 
when i use 'MONGO_PU', kundera using elasticsearch to  execute the queries automatic.
because i defined a property:
<property name="kundera.indexer.class" value="com.impetus.client.es.index.ESIndexer" />
In this case, q.setFirstResult(20) doesn't effective. and 'count' result is wrong too.

when i use MONGO_NTV (pure mongodb, not using es), the problem is 'count' not working, because i not using it in native way. i will try it again in native way.

**Comment by chhavigangwal** [comment] 2016-01-06 12:25
Is there a specific use case where you need to use Mongo with ES ?  Let us know. As most of your requirements should be catered by MongoDB native query .

Chhavi

**Comment by dreamingo88** [comment] 2016-01-06 13:05
@chhavigangwal 
thank you for your suggestion.
i think full-text search is not mongdb's specialty, especially when using chinese.
so i hope to use es to implement full-text search feature.

**Comment by chhavigangwal** [comment] 2016-01-06 13:21
@dreamingo88 

Alright, we will try to enable and test this in our upcoming release and update you about the same shortly.

Chhavi

**Comment by dreamingo88** [comment] 2016-01-06 13:34
@chhavigangwal 
Thanks! 
It's a very good news to me. 
Looking forward for the next version.

**Comment by chhavigangwal** [comment] 2016-01-12 12:45
@dreamingo88 

A fix for adhoc querying via Elastic search is added , you can test the same by building our current trunk code. The same will be released with 3.3.

Chhavi

**Comment by dreamingo88** [comment] 2016-01-13 06:40
@chhavigangwal 
Thanks for your great work! I will try when 3.3 released.

What about 'count' supported in mongodb and es, i mean using jpql instead of native query.
I think the most important reason about developers use kundera was we can use jpql to do most things, we don't need to master too many query languages. so i hope kundera can implement most of jpql features for the nosql systems supported by kundera.

Another suggestion: If there have some tutorials about how to implement jpql features, i think more contributors can do something.

Kundera is a great project, I will continue to focus on kundera.

**Comment by chhavigangwal** [comment] 2016-01-16 04:05
@dreamingo88 
- Count is supported using when using esindexer
  Please find the test cases for your reference to start using ES with MongoDB at : https://github.com/impetus-opensource/Kundera/tree/trunk/src/kundera-mongo/src/test/java/com/impetus/client/esindexer 

To answer to your last question , Kundera currently has a core framework which client extends and implements  . +1 for your suggestion for adding a tutorial , but for now you can refer to following thread to get a basic understanding of how client modules integrate with Kundera.

Please feel free to write to us at kundera@impetus.co.in , in case you have any queries.

Would you like to share for which use case are you using Kundera ?

Chhavi

**Closed as completed by chhavigangwal** 2016-01-16 04:05 UTC
Labels: Fixed
