### ISSUE TITLE
Uncessary new Cluster and Session objects in DSClient constructor

### ISSUE THREAD

**Issue by neasoon** [Impetus/kundera#769] opened 2015-08-04 18:24 UTC
Every time a new DSClient is created, the constructor calls factory.createPoolOrConnection() which results in the creation of a new Cluster and Session. The cluster and session are initially created  along with the DSClientFactory and we should be able to use them for the whole lifetime of the factory object.

``` java
    public DSClient(DSClientFactory factory, String persistenceUnit, Map<String, Object> externalProperties,
            KunderaMetadata kunderaMetadata, EntityReader reader, final TimestampGenerator generator)
    {
        super(persistenceUnit, externalProperties, kunderaMetadata, generator);
        this.factory = factory;
        this.reader = reader;
        this.clientMetadata = factory.getClientMetadata();
        factory.createPoolOrConnection();
        this.setCqlVersion(CassandraConstants.CQL_VERSION_3_0);
    }
```

**Comment by karthikprasad13** [comment] 2015-08-11 08:01
@neasoon 

Your code is not consistent with Kundera's trunk.

Please refer [`DSClient.java`](https://github.com/impetus-opensource/Kundera/blob/4ab46233e39b87c5516e0f870dd581b79eaac265/src/kundera-cassandra/cassandra-ds-driver/src/main/java/com/impetus/kundera/client/cassandra/dsdriver/DSClient.java#L113)

-Karthik.

**Comment by karthikprasad13** [comment] 2015-09-21 06:12
@neasoon 

Closing the issue since its not a bug. Please comment if you have further queries.

-Karthik

**Closed as completed by karthikprasad13** 2015-09-21 06:12 UTC
Labels: UserResponseAwaited
