### ISSUE TITLE
Problems connecting to Cassandra with remote server and password authentication

### ISSUE THREAD

**Issue by Allekto** [Impetus/kundera#343] opened 2013-08-02 13:03 UTC
0 down vote favorite

I try to connect my play application to Cassandra DB. I tried this tutorial: http://xamry.wordpress.com/2013/07/06/play-nosql-building-nosql-applications-with-play-framework/

The difference in my setup is that cassandra is not on my localhost, but in one of my servers in the internet. To keep my cassandra installation secure i also used password authorization instead of the AllowAll authorization used on local installs.

So i added those two lines to my persistance.xml:

```
<property name="kundera.username" value="user" />
<property name="kundera.password" value="passwd" />
```

However i have problems running the application. It seems that i cant get authorized:

[KunderaException: com.impetus.kundera.KunderaException: InvalidRequestException(why:You have not logged in)] 
user.setLastName("Smith");

24 user.setCity("London");

25

26 em.persist(user);

27 em.close();

28 return ok("User 0001 record persisted for persistence unit cassandra_pu");

29 }

30

31 public static Result find()

So i am wondering what do i have to do to log in to Cassandra? All the examples on the net i could find are only for this localhost/allowEverything scenario. What do i have to do, to get this example running in a production environment with real servers and real passwords?

**Comment by impetus-opensource-admin** [comment] 2013-08-02 13:06
Duplicate of https://github.com/impetus-opensource/Kundera/issues/328

PS: This issue is specific to ThriftclientFactory working with PelopsClientFactory.

-Vivek

**Comment by mevivs** [comment] 2013-08-07 12:24
Fixed in current trunk.Please verify.

-Vivek

**Closed as completed** 2013-08-22 09:49 UTC
