### ISSUE TITLE
kundera.client property is missing for persistence unit, version 2.10

### ISSUE THREAD

**Issue by gmatej** [Impetus/kundera#536] opened 2014-02-25 16:59 UTC
When testing kundera 2.10 with tomee 1.6 I get an exception like this:
java.lang.IllegalArgumentException: kundera.client property is missing for persistence

Similliar to this SO post. Alzough I am not using spring.
http://stackoverflow.com/questions/21700915/error-kundera-client-property-is-missing-for-persistence

When changing to 2.9.1, everything works.

**Comment by mevivs** [comment] 2014-02-25 18:02
Defining persistence properties as part of persistence.xml or as an external property map?

-Vivek

**Comment by gmatej** [comment] 2014-02-25 20:31
Yes, as persistence.xml file

Matej

**Comment by mevivs** [comment] 2014-02-26 03:53
Please share crud code snippet and persistence.xml

-Vivek

**Comment by gmatej** [comment] 2014-02-26 08:36
It's very simple setup. Altough I have 2 PU units. Today I reproduced the problem, only cganging version number from 2.9.1 to 2.10. Produces me the kundera.client property error.

 @GET
    public Response getResources() {

```
    KunderaUser kunderaUser = new KunderaUser();
    kunderaUser.setUserId("1");
    kunderaUser.setFirstName("Name");
    em.persist(kunderaUser);

    return Response.ok().build();
}

<persistence-unit name="bookPersistenceUnit" transaction-type="JTA">
    <provider>org.apache.openjpa.persistence.PersistenceProviderImpl</provider>
    <jta-data-source>jdbc/book</jta-data-source>
    <class>com.book.model.AppUser</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
    </properties>
</persistence-unit>
<persistence-unit name="bookCassandraPersistenceUnit">
    <provider>com.impetus.kundera.KunderaPersistence</provider>
    <class>com.book.model.KunderaUser</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
        <property name="kundera.nodes" value="localhost" />
        <property name="kundera.port" value="9160" />
        <property name="kundera.keyspace" value="book" />
        <property name="kundera.dialect" value="cassandra" />
        <property name="kundera.ddl.auto.prepare" value="update" />
        <property name="kundera.client" value="thrift" />
        <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.thrift.ThriftClientFactory" />
    </properties>
</persistence-unit>
```

**Comment by mevivs** [comment] 2014-02-26 08:40
Thanks. Could you please email me sample project at vivek.mishra@impetus.co.in for quick resolution?

-Vivek

**Comment by janinko** [comment] 2014-02-26 14:55
I had the same issue with 2.10. Isn't there a inverted condition here?
https://github.com/impetus-opensource/Kundera/blob/kundera-2.10/src/jpa-engine/core/src/main/java/com/impetus/kundera/configure/PersistenceUnitConfiguration.java#L133

**Comment by mevivs** [comment] 2014-02-26 15:35
Duplicate of https://github.com/impetus-opensource/Kundera/issues/526?

-Vivek

**Comment by tsbatista** [comment] 2014-02-26 18:21
I have the same use case as this. If i set the property, i get the exception mentioned by janinko. If i unset it from my persistence.xml, i get the message from https://github.com/impetus-opensource/Kundera/blob/kundera-2.10/src/jpa-engine/core/src/main/java/com/impetus/kundera/metadata/model/PersistenceUnitMetadata.java#L532

Looking at both conditions, I would say that even if this is related to #526, the if condition on the PersistenceUnitConfiguration still needs to be checked as i think there is a contradiction there.

**Comment by mevivs** [comment] 2014-02-26 18:25
With fix provided for #526, i guess, additional check on
https://github.com/impetus-opensource/Kundera/blob/kundera-2.10/src/jpa-engine/core/src/main/java/com/impetus/kundera/metadata/model/PersistenceUnitMetadata.java#L532

https://github.com/impetus-opensource/Kundera/blob/kundera-2.10/src/jpa-engine/core/src/main/java/com/impetus/kundera/configure/PersistenceUnitConfiguration.java#L133

not required.As it is implicitly handled before invocation of getClient().  PersistenceUnitMetadata and PersistenceUnitConfiguration are meant for properties specific for persistence.xml.

Please verify with latest trunk. It should work.

-Vivek

**Comment by tsbatista** [comment] 2014-02-26 18:46
I think this particular issue is now solved.  That was fast!!!

Thank you

**Comment by gmatej** [comment] 2014-02-27 09:28
Vivek.

Is this issue closed or would you need the small project still?
Btw, this is sure OK?
            if (puInfo.getProperties().getProperty(PersistenceProperties.KUNDERA_CLIENT_FACTORY) != null)

Best regards

Matej

**Comment by mevivs** [comment] 2014-02-27 09:43
Yes, i guess it should work. Could you please verify it with latest trunk?

-Vivek

**Comment by pires** [comment] 2014-02-27 11:55
I said this before, but here I come again. It would be great if commits would reference issues in the commit logs. That way, people could know what changes have been made to fix an issue, and eventually participate in reviewing it.

**Comment by mevivs** [comment] 2014-02-27 11:57
As mentioned above, duplicate of #526. Indirectly fixed with https://github.com/impetus-opensource/Kundera/issues/526. Commit history is available over there.

-Vivek

**Comment by gmatej** [comment] 2014-02-28 07:57
I ahve tried it. It works.

Altough had to disable units tests:)

Thanks!

Matej

**Closed as completed** 2014-03-28 09:03 UTC
