### ISSUE TITLE
Generate wrong table while using UDT(user define type)

### ISSUE THREAD

**Issue by ankit5858** [Impetus/kundera#719] opened 2015-03-13 09:50 UTC
Hi, we got a problem while creating UDT table, we are using [cqlsh 5.0.1 | Cassandra 2.1.2 | CQL spec 3.2.0 | Native protocol v3]
## Kundera create as..

CREATE TABLE samplekund.officer (
    key text,
    column1 text,
    value blob,
    column2 text,
    PRIMARY KEY (key, column1)
## ) ;

Instead of ..
CREATE TABLE samplekund.officer (
    Id int PRIMARY KEY,
    city text,
    state text,
    addressType text,
    phoneType frozen<PhoneType>

);
## blow are my pojo class

@Entity
@Table(name="address",schema="sampleapp@cassandra_pu")
public class Address {

```
@Id
@Column
private int Id;
@Column
private String city;
@Column
private String state;
@Column
private String addressType;
@Embedded
private PhoneType phoneType;
```

}

@Embeddable
public class PhoneType {

```
@Column(name="home_phone")
private long homePh;
@Column(name="mobile_phone")
private long mobilePh;
```

}

**Comment by karthikprasad13** [comment] 2015-03-13 10:18
@ankit5858 

Support for UDT's are enabled from kundera-cassandra 2.15.1 onwards. Please update your dependencies for the same. Also check [Wiki](https://github.com/impetus-opensource/Kundera/wiki/Support-for-User-Defined-Types-and-Indexes-on-Collections) for more details.

-Karthik.

**Comment by chhavigangwal** [comment] 2015-03-16 04:37
Duplicate of #720

**Closed as completed by chhavigangwal** 2015-03-16 04:37 UTC
