### ISSUE TITLE
Getting exception when using kundera.ddl.auto.prepare as validate

### ISSUE THREAD

**Issue by tarunsas** [Impetus/kundera#538] opened 2014-02-26 23:11 UTC
Hi,

Posted on google code also.

Exception stack trace

We have an Entity with composite columns using @EmbeddedId, when we try to use ddl.auto.prepare with validate, it throws an error.

Even though the column family exists in keyspace, it is not able to find it.

15:31:20,411 ERROR CassandraSchemaManager:438 - Error occurred while validating grid, Caused by: .
com.impetus.kundera.configure.schema.SchemaGenerationException: Column family EnablerCustomerAccountInfo does not exist in keyspace grid
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onValidateTable(CassandraSchemaManager.java:999)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onValidateTables(CassandraSchemaManager.java:970)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.validate(CassandraSchemaManager.java:434)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:258)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:108)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:142)
    at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:188)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:45)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:357)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:115)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:48)
    at xxxx.xxxx.CassandraPersistenceFactoryHelper.getDefaultEntityManager(CassandraPersistenceFactoryHelper.java:180)
    at xxxx.xxxx.CassandraPersistenceFactoryHelper.getEntityManager(CassandraPersistenceFactoryHelper.java:133)
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:72)
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:45)
    at xxxx.xxxxjpa.test.JpaTest.processCommand(JpaTest.java:127)
    at xxxx.xxxxjpa.test.JpaTest.enterCommandMode(JpaTest.java:79)
    at xxxx.xxxxjpa.test.JpaTest.main(JpaTest.java:54)
15:31:20,412 ERROR CassandraGridProviderImpl:82 - com.impetus.kundera.configure.schema.SchemaGenerationException: Column family EnablerCustomerAccountInfo does not exist in keyspace grid
com.impetus.kundera.configure.schema.SchemaGenerationException: com.impetus.kundera.configure.schema.SchemaGenerationException: Column family EnablerCustomerAccountInfo does not exist in keyspace grid
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.validate(CassandraSchemaManager.java:439)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:258)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:108)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:142)
    at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:188)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:45)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:357)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:115)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:48)
    at xxxx.xxxx.CassandraPersistenceFactoryHelper.getDefaultEntityManager(CassandraPersistenceFactoryHelper.java:180)
    at xxxx.xxxx.CassandraPersistenceFactoryHelper.getEntityManager(CassandraPersistenceFactoryHelper.java:133)
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:72)
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:45)
    at xxxx.xxxxjpa.test.JpaTest.processCommand(JpaTest.java:127)
    at xxxx.xxxxjpa.test.JpaTest.enterCommandMode(JpaTest.java:79)
    at xxxx.xxxxjpa.test.JpaTest.main(JpaTest.java:54)
Caused by: com.impetus.kundera.configure.schema.SchemaGenerationException: Column family EnablerCustomerAccountInfo does not exist in keyspace grid
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onValidateTable(CassandraSchemaManager.java:999)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onValidateTables(CassandraSchemaManager.java:970)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.validate(CassandraSchemaManager.java:434)
    ... 16 more
xxxx.xxxx.exceptions.GridException: Error creating GridBag instance.
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:83)
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:45)
    at xxxx.xxxxjpa.test.JpaTest.processCommand(JpaTest.java:127)
    at xxxx.xxxxjpa.test.JpaTest.enterCommandMode(JpaTest.java:79)
    at xxxx.xxxxjpa.test.JpaTest.main(JpaTest.java:54)
Caused by: com.impetus.kundera.configure.schema.SchemaGenerationException: com.impetus.kundera.configure.schema.SchemaGenerationException: Column family EnablerCustomerAccountInfo does not exist in keyspace grid
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.validate(CassandraSchemaManager.java:439)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:258)
    at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:108)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:142)
    at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:188)
    at com.impetus.kundera.configure.ClientMetadataBuilder.buildClientFactoryMetadata(ClientMetadataBuilder.java:45)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.configureClientFactories(EntityManagerFactoryImpl.java:357)
    at com.impetus.kundera.persistence.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:115)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:83)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:48)
    at xxxx.xxxx.CassandraPersistenceFactoryHelper.getDefaultEntityManager(CassandraPersistenceFactoryHelper.java:180)
    at xxxx.xxxx.CassandraPersistenceFactoryHelper.getEntityManager(CassandraPersistenceFactoryHelper.java:133)
    at xxxx.xxxx.CassandraGridProviderImpl.createGridBag(CassandraGridProviderImpl.java:72)
    ... 4 more
Caused by: com.impetus.kundera.configure.schema.SchemaGenerationException: Column family EnablerCustomerAccountInfo does not exist in keyspace grid
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onValidateTable(CassandraSchemaManager.java:999)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onValidateTables(CassandraSchemaManager.java:970)
    at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.validate(CassandraSchemaManager.java:434)

**Comment by mevivs** [comment] 2014-02-27 01:38
Looking into this and will post an update.

-Vivek

**Comment by mevivs** [comment] 2014-02-27 01:43
Looks like duplicate of https://github.com/impetus-opensource/Kundera/issues/500

-Vivek

**Comment by mevivs** [comment] 2014-02-27 11:16
Hi,
Fix has been added for this issue. Reason for this issue:
1. kundera.ddl.auto.prepare with "validate" option is now supporting CQL3 based columnfamilies(tables), earlier it was not.

Please have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/schemamanager/CassandraSchemaManagerTest.java#L133

You need to explicitly set for CQL version to 3.0 as:

```
 propertyMap.put(CassandraConstants.CQL_VERSION,CassandraConstants.CQL_VERSION_3_0)
```

Please verify with latest trunk.

**Comment by tarunsas** [comment] 2014-02-27 14:05
Vivek,

We are using 2.9.1, so which version we need to migrate to ? . Also will it be published to public repository?

Thanks
sriram

**Comment by mevivs** [comment] 2014-02-27 16:38
Issue is fixed on latest trunk. You need to manually build it.

-Vivek

**Comment by tarunsas** [comment] 2014-02-27 18:48
Can you give me the link to check out and test it? Also what will be timeline and version number for next release.

**Comment by mevivs** [comment] 2014-02-27 18:59
2.11 is slated to release around 21st March. 

Steps to build snapshot locally:
1. git clone https://github.com/impetus-opensource/Kundera.git
2. mvn clean install -DskipTests
3. change dependency version to 2.11-SNAPSHOT

-Vivek

**Comment by tarunsas** [comment] 2014-02-27 20:44
Thanks vivek,

When build and use 2.11-SNAPSHOT.

We get lot of our tests failing, especially i see when i have OneToMany. It is failing.

@Entity
@Table(name = "EdgeUverseInfo", schema = "grid@cassandra_pu")
public class EdgeUverseInfo implements Serializable {

```
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
@JoinColumn(name = "workRequests")
protected List<WorkRequest> workRequests;
```

persistence.xml

Note: This is failing against embedded cassandra.(>1.2)

14:35:57,237  INFO CassandraClientBase:1039 - Returning cql query  INSERT INTO "EdgeUverseInfo"("key") VALUES('25af688c-eb14-4a2e-a218-4057aea9a98a') .
14:35:57,237  INFO CassandraClientBase:1039 - Returning cql query  INSERT INTO "WorkRequest"("workRequestId","key","workRequests","workRequests") VALUES('123123123','uniqueId','25af688c-eb14-4a2e-a218-4057aea9a98a','16819b62-6740-4405-9dcf-e661b495c60c') .
14:35:57,238 ERROR CassandraClientBase:1896 - Error during executing query BEGIN BATCH   INSERT INTO "EdgeUverseInfo"("key") VALUES('25af688c-eb14-4a2e-a218-4057aea9a98a')  USING TTL 99999999 INSERT INTO "WorkRequest"("workRequestId","key","workRequests","workRequests") VALUES('123123123','uniqueId','25af688c-eb14-4a2e-a218-4057aea9a98a','16819b62-6740-4405-9dcf-e661b495c60c')  APPLY BATCH, Caused by: InvalidRequestException(why:Multiple definitions found for column workRequests) .
14:35:57,239 ERROR CassandraClientBase:1603 - Error while persisting record. Caused by: .
14:35:57,239 ERROR CassandraClientBase:1603 - Error while persisting record. Caused by: .
javax.persistence.PersistenceException: InvalidRequestException(why:Multiple definitions found for column workRequests)
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1898)
    at com.impetus.client.cassandra.CassandraClientBase.executeBatch(CassandraClientBase.java:1598)
    at com.impetus.kundera.persistence.PersistenceDelegator.execute(PersistenceDelegator.java:832)
    at com.impetus.kundera.persistence.PersistenceDelegator.doFlush(PersistenceDelegator.java:745)
    at com.impetus.kundera.persistence.EntityManagerImpl.flush(EntityManagerImpl.java:386)
    at xxxx.xxxx.CassandraGridBagImpl.putKundera(CassandraGridBagImpl.java:357)
    at xxxx.xxxx.CassandraGridBagImpl.put(CassandraGridBagImpl.java:128)
    at xxxx.xxxx.CassandraGridBagImpl.put(CassandraGridBagImpl.java:142)
    at xxxx.xxxx.CassandraGridBagImpl.put(CassandraGridBagImpl.java:154)
    at xxxx.xxxx.CassandraGridBagImpl.put(CassandraGridBagImpl.java:161)
    at xxxx.xxxx.GridTest.testPut(GridTest.java:795)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:69)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:120)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:104)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: InvalidRequestException(why:Multiple definitions found for column workRequests)
    at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
    at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
    at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1882)
    ... 38 more

**Comment by mevivs** [comment] 2014-02-28 04:24
Issue with this query is:
INSERT INTO "WorkRequest"("workRequestId","key","workRequests","workRequests") 

"workRequests" is occuring twice in CQL query, which seems incorrect.

Please share entity definition for EdgeUverseInfo and WorkRequest entities

-Vivek

**Comment by tarunsas** [comment] 2014-02-28 17:28
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EdgeUverseInfo", propOrder = { "workRequests" })
@Entity
@Table(name = "EdgeUverseInfo", schema = "grid@cassandra_pu")
public class EdgeUverseInfo implements Serializable {

```
@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
@JoinColumn(name = "workRequests")
protected List<WorkRequest> workRequests;
```

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkRequest")
@Entity
@Table(name = "WorkRequest", schema = "grid@cassandra_pu")
public class WorkRequest implements Serializable {

```
@XmlAttribute(name = "workRequestKey")
@Id
protected String workRequestKey;
```

The same works fine with prev versions.

**Comment by mevivs** [comment] 2014-02-28 18:45
This looks ok. However this is not complete entity definition.
As per the generated insert query, 

```
 INSERT INTO "WorkRequest"("workRequestId","key","workRequests","workRequests") VALUES('123123123','uniqueId','25af688c-eb14-4a2e-a218-4057aea9a98a','16819b62-6740-4405-9dcf-e661b495c60c') .
```

looks like 2 attributes are mapped with same name(e.g. "workRequests"). Which is causing this issue. You can't have 2 columns with same name.

Please verify if there is any other attribute either annotated with @Column(name="workRequests") present or attribute name itself is "workRequests".

-Vivek

**Comment by tarunsas** [comment] 2014-02-28 18:48
The same entity works with 2.9.1

attribute name is workRequests.

Entity is WorkRequest.

**Comment by mevivs** [comment] 2014-02-28 18:51
@tarunsas
I understand that it works with 2.9.1. Either provide complete entity definition and crud code snippet to reproduce it at my end. You can email me sample project at vivek.mishra@impetus.co.in

-Vivek

**Closed as completed** 2014-03-28 09:03 UTC
