### ISSUE TITLE
Cql can't map PK right to entity by using kunder2.4 + cassandra1.2.2 !!!!!!!

### ISSUE THREAD

**Issue by zhouhero** [Impetus/kundera#214] opened 2013-03-14 12:14 UTC
I used the following cql to search the data,  the PK column is not right mapping to entity class. 

---
## select \* from test1 where key in (1,2,3)

by the way, the table is created not by cassandra-cli not by cql.
It very important to me ,can anyone help me?

**Comment by mevivs** [comment] 2013-03-14 12:19
Hi,
Can you please a bit more on this?

-Vivek

**Comment by mevivs** [comment] 2013-03-14 13:48
Looking for more description around this, please provide it.

-Vivek

**Comment by zhouhero** [comment] 2013-03-15 01:29
- My Table:
  create column family test with comparator = UTF8Type and key_validation_class=Int32Type and   column_metadata =
  [
  {column_name:userid, validation_class:UUIDType}
  {column_name:url, validation_class:UTF8Type}
  {column_name:datetime, validation_class:DateType}
  {column_name:linkcount, validation_class:Int32Type}
  ];
- My Entity:
  @Entity
  @Table(name = "test", schema = XXXXX)
  @XmlRootElement(name = "TestEntity")
  public class TestEntity implements Serializable {
  
  private static final long serialVersionUID = 1L;
  
  @Id
  @Column(name = "id")
  private int id;
  
  @Column(name = "userid")
  private UUID userid;
  
  @Column(name = "url")
  private String url;
  
  @Column(name = "datetime")
  private Timestamp datetime;
  
  @Column(name = "linkcounts")
  private int linkcounts;
  ...
  ...
  ...
- My test program:

TestEntity test1 = new TestEntity();
test1.setId(1);
test1.setUrl("1");

entityManager.persist(test1);
entityManager.flush();

TestEntity test2 = new TestEntity();
test2.setId(2);
test2.setUrl("2");
entityManager.persist(test2);
entityManager.flush();

TestEntity test3 = new TestEntity();
test3.setId(3);
test3.setUrl("3");
entityManager.persist(test3);
entityManager.flush();

String cql = "select \* from test where key in (1,2,3)";

Query query = entityManager.createNativeQuery(cql, TestEntity.class);
List<TestEntity> list = (List<TestEntity>) query.getResultList();

if (list != null) {
 for (TestEntity e : list) {
   System.out.println(e.getId());
 }
}
- RESULT:
  the output of e.getId() is always 0!

**Comment by zhouhero** [comment] 2013-03-15 01:30
can you help me check this problem?

**Comment by mevivs** [comment] 2013-03-15 01:42
Yes.. i am looking into this.

-Vivek

**Comment by zhouhero** [comment] 2013-03-15 02:05
by the way, not only "in" keyword, the normal cql searching can not do well .
like:
 "select \* from test where key =1";

**Comment by mevivs** [comment] 2013-03-15 02:16
Hi,
I have looked into this issue. As a workaround If you change: 

```
@Id
@Column(name = "id")
private int id;
```

as

```
@Id
@Column(name = "key")
private int id;
```

It should work. I will have a look and will provide a proper fix for this.

-Vivek

**Comment by zhouhero** [comment] 2013-03-15 02:22
thanks for  your idea, 
i have done it like you  said also,
it can does well now.
but this is a bug need to fix , i think.

**Comment by mevivs** [comment] 2013-03-15 02:33
This can be computed implicitly. With Cassandra 1.2 onwards CQL3 does not return id field as key with CqlRow object, but as a column with a name "key"(Earlier it was not the case).I did post some queries around this on cassandra user community. So if you give column name as "key" it will work. 

Though name of column attribute annotated with @Column annotation is irrelevant as Cassandra does not use this name as a row key name(it is not possible to define a name for row key in cassandra). So such computations are done within Kundera. I will get it done but i  don't see a much of value add with this.

Hope it clarifies the cause behind this issue.

-Vivek

**Comment by zhouhero** [comment] 2013-03-15 02:47
by the way ,
when i creat table like fellow , i think the pk column name is return to "id" not "key" by cql

create columnfamily test (id int primary key, url text, userid uuid, datetime timestamp, linkcounts int);

**Comment by zhouhero** [comment] 2013-03-15 02:48
at this time, the pk name should like fellow, i think. is it right?
@Column(name = "id")

**Comment by mevivs** [comment] 2013-03-15 03:05
yes. i see your point , it should not be an issue after interoperability support b/w cql and thrift.(planned for 2.5)

**Comment by zhouhero** [comment] 2013-03-15 03:08
thank you very much,
when will kundera 2.5 release?

**Comment by mevivs** [comment] 2013-04-29 23:06
Releasing with 2.5, please verify.

-Vivek

**Closed as completed** 2013-07-09 10:00 UTC
