### ISSUE TITLE
Support Kundera-cassandra criteria count

### ISSUE THREAD

**Issue by uladzimirFilipchanka** [Impetus/kundera#735] opened 2015-04-10 11:48 UTC
Hello,
As far as I understand there is not support for 'count' query in JPA Criteria. 
I mean something like this: 

```
CriteriaBuilder qb = entityManager.getCriteriaBuilder();
CriteriaQuery<Long> cq = qb.createQuery(Long.class);
cq.select(qb.count(cq.from(MyEntity.class)));
cq.where(/*your stuff*/);
return entityManager.createQuery(cq).getSingleResult();
```

In 2.16 I see that KunderaCriteriaBuilder.count returns null.
Are you going to add implementations for count queries in near releases? It would be greate!
Is there any option or workaround to use count exactly in JPA Criteria? 
Any help would be appreciated!

**Comment by mevivs** [comment] 2015-04-10 11:56
AFAIK, you can execute native CQL3 query to get count using Kundera.

-Vivek

**Comment by uladzimirFilipchanka** [comment] 2015-04-10 12:03
Yep, right
But unfortunately we have dynamic queries which depend on incoming data. And the best choice is to use criteria. Plus we already use them for selecting data. Need only count.

**Comment by mevivs** [comment] 2015-04-10 12:08
Guess, still it is possible but yes as a workaround. But adding count via criteriaQuery would be most optimal solution.

-Vivek

**Comment by uladzimirFilipchanka** [comment] 2015-04-10 14:08
Do you have any plans to add this in near feature?

**Comment by mevivs** [comment] 2015-04-10 14:39
@uladzimirFilipchanka 
Let me try to find sometime and see if i can share a patch to get this working.

**Comment by uladzimirFilipchanka** [comment] 2015-04-13 11:21
@mevivs
Thanks, looking forward to your reply!

**Comment by chhavigangwal** [comment] 2015-05-09 14:45
Fixed with Kundera -2.17 release.

**Closed as completed by chhavigangwal** 2015-05-09 14:45 UTC
Labels: Fixed

**Comment by uladzimirFilipchanka** [comment] 2015-06-08 10:15
Hello, 
We've testes count in JPA criteria. The following code

```
    CriteriaBuilder qb = getEM().getCriteriaBuilder();
    CriteriaQuery<Long> cq = qb.createQuery(Long.class);
    Root<MyEntity> from = cq.from(MyEntity.class);
    cq.select(qb.count(from));
    cq.where(qb.equal(from.get("lastName"), "lastname123"));
    getEM().createQuery(cq).getSingleResult();
```

fails with "Mismatch in expected return type. Expected:class java.lang.Long But actual class is:class org.ustaxi.app.cassandra.model.MyEntity"

Short stacktrace:

```
    com.impetus.kundera.persistence.EntityManagerImpl.onTypedQuery(EntityManagerImpl.java:968)
    com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:723)
    com.impetus.kundera.persistence.EntityManagerImpl.createQuery(EntityManagerImpl.java:709)
```

**Comment by karthikprasad13** [comment] 2015-06-08 13:33
@uladzimirFilipchanka 

Please use `Object.class` while creating `CriteriaQuery`. Following should work (assuming you are using `CQL version 3`):

```
    CriteriaBuilder qb = getEM().getCriteriaBuilder();
    CriteriaQuery<Object> cq = qb.createQuery(Object.class);
    Root<MyEntity> from = cq.from(MyEntity.class);
    cq.select(qb.count(from));
    cq.where(qb.equal(from.get("lastName"), "lastname123"));
    Object result = getEM().createQuery(cq).getSingleResult();
```

You can then cast the result into `Map` and get count by `result.get("count")`

-Karthik

**Comment by marcelooliveiragualberto** [comment] 2017-02-08 18:12
In my project, after include "Object result = getEM().createQuery(cq).getSingleResult();", i have this error:

Exception in thread "main" com.impetus.kundera.property.PropertyAccessException: java.lang.IllegalArgumentException: Can not set java.lang.String field br.com.taticasolutions.anrcompare.taticaanalytics.model.Filter.id to java.util.HashMap
	at com.impetus.kundera.property.PropertyAccessorHelper.getObject(PropertyAccessorHelper.java:144)
	at com.impetus.kundera.property.PropertyAccessorHelper.getId(PropertyAccessorHelper.java:245)
	at com.impetus.kundera.query.QueryImpl.addToRelationStack(QueryImpl.java:274)
	at com.impetus.kundera.query.QueryImpl.setRelationEntities(QueryImpl.java:234)
	at com.impetus.client.cassandra.query.CassQuery.recursivelyPopulateEntities(CassQuery.java:284)
	at com.impetus.kundera.query.QueryImpl.fetch(QueryImpl.java:1377)
	at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:200)
	at com.impetus.kundera.query.QueryImpl.getSingleResult(QueryImpl.java:761)
	at com.impetus.kundera.query.KunderaTypedQuery.getSingleResult(KunderaTypedQuery.java:261)
	at br.com.taticasolutions.anrcompare.dao.GenericDAO.count(GenericDAO.java:181)
	at br.com.taticasolutions.test.TestPersistence.main(TestPersistence.java:59)
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.String field br.com.taticasolutions.anrcompare.taticaanalytics.model.Filter.id to java.util.HashMap
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.impetus.kundera.property.PropertyAccessorHelper.getObject(PropertyAccessorHelper.java:140)
	... 10 more

>>> follow my code block:

		EntityManager em = emf.createEntityManager();
		CriteriaBuilder qb = em.getCriteriaBuilder();
		CriteriaQuery<Object> cq = qb.createQuery(Object.class);
		Root<Filter> from = cq.from(Filter.class);
		cq.select(qb.count(from));
		Object result = em.createQuery(cq).getSingleResult();

**Comment by karthikprasad13** [comment] 2017-02-09 07:29
@marcelooliveiragualberto 

Can you share the contents of your `Filter` entity?

-Karthik

**Comment by marcelooliveiragualberto** [comment] 2017-02-09 13:25
@karthikprasad13

Sure, follow below..

```
package br.com.taticasolutions.anrcompare.taticaanalytics.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.javatuples.Pair;

import br.com.taticasolutions.anrcompare.enums.Enums.TypeOfComponent;
import br.com.taticasolutions.anrcompare.enums.Enums.YesOrNo;
import br.com.taticasolutions.anrmodel.domain.base.ABaseEntity;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * The persistent class for the TBL_FILTER database table.
 *
 */
@Entity
@Table(name = "tbl_filter")
@NamedQueries(value = {
	@NamedQuery(name = "Filter.findAll", query = "SELECT f FROM Filter f"),
	@NamedQuery(name = "Filter.findAllParent", query = "SELECT f FROM Filter f WHERE f.filter is not null"),
	@NamedQuery(name = "Filter.findByReportID", query = "SELECT f FROM Filter f LEFT JOIN f.reports rep WHERE rep.id = :id")
})
@ToString
@Getter
@Setter
public class Filter extends ABaseEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private String id;

	@Column(name = "change_variable_value")
	private String changeVariableValue;

	private BigDecimal order;

	@Column(name = "query_value")
	private String queryValue;

	@Enumerated(EnumType.ORDINAL)
	private YesOrNo required;

	@Column(name = "screen_label")
	private String screenLabel;

	@Column(name = "screen_name")
	private String screenName;

	@Enumerated(EnumType.ORDINAL)
	private TypeOfComponent type;

	@Column(name = "variable_name")
	private String variableName;

	// bi-directional many-to-one association to Filter
	@ManyToOne
	@JoinColumn(name = "parent")
	private Filter filter;

	// bi-directional many-to-one association to Filter
	@OneToMany(mappedBy = "filter", fetch = FetchType.EAGER)
	private List<Filter> filters;

	// bi-directional many-to-many association to Report
	@ManyToMany(mappedBy = "filters")
	private List<Report> reports;

	@Transient
	private Object value;
	@Transient
	private List<Object> listValue;
	@Transient
	private List<Pair<String, Object>> list;

	public Filter() {
	}

	@Override
	public String getEntityIdentifier() {
		return id;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Filter other = (Filter) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
```

Tks!!

**Comment by crashedserver** [comment] 2017-08-17 14:10
Did it work? Does not work for me throws ClassCastException
