### ISSUE TITLE
com.impetus.kundera.query.JPQLParseException: Out of order keyword from, entity alias must not be any reserved keyword..

### ISSUE THREAD

**Issue by zeremit** [Impetus/kundera#664] opened 2014-11-17 14:42 UTC
I write such JPA Query
@Test
  public void testKeyWordFail(){
        CriteriaBuilder criteriaBuilder = emp.getCriteriaBuilder();
        CriteriaQuery<User> query = criteriaBuilder.createQuery(User.class);
        Root<User> from = query.from(User.class);
        query.select(from.alias("t"));
        query.where(criteriaBuilder.equal((Expression) from.get("name"), "Screenshot from 2013-10-30 17:43:51.png"));
        TypedQuery<User> typedQuery =emp.createQuery(query);
        List<User> result = typedQuery.getResultList();
    }
and catch error on line : TypedQuery<User> typedQuery =emp.createQuery(query);
Is it posible to create query like
'Select \* from user where user.name="Screenshot from 2013-10-30 17:43:51.png"' ?
Work code on https://github.com/zeremit/kundera-example

**Comment by chhavigangwal** [comment] 2014-11-18 10:37
@zeremit 

The issue is with the use of keyword "from" in the string of where clause which throws the exception. We are looking into the issue.

Chhavi

**Comment by chhavigangwal** [comment] 2015-09-16 07:28
Resolved, closing with Kundera 3.1 release

**Closed as completed by chhavigangwal** 2015-09-16 07:28 UTC
Labels: Fixed
