### ISSUE TITLE
Using Collections.EMPTY_SET or Collections.EMPTY_MAP causes a NullPointerException

### ISSUE THREAD

**Issue by pdirksen** [Impetus/kundera#511] opened 2014-01-22 12:10 UTC
An additional warning appears:

Warnung: Returning null as error during clone, Caused by:Class com.impetus.kundera.utils.ObjectUtils can not access a member of class java.util.Collections$EmptySet with modifiers "private".

Instantiating a new HashMap oder a new HashSet solves it, but EmptySet and EmptyMap should work too.

**Comment by mevivs** [comment] 2014-01-22 12:20
Duplicate of https://github.com/impetus-opensource/Kundera/issues/381 ?

**Comment by pdirksen** [comment] 2014-01-24 14:37
The cause is a duplicate yes.

**Comment by impetus-opensource-admin** [comment] 2014-05-12 07:29
Closing ... the duplicate issues. Please track through #381.

**Closed as completed by impetus-opensource-admin** 2014-05-12 07:29 UTC
